[package]
name = "definitely_not_pong"
version = "0.1.0"
edition = "2021"
# cargo watch -q -c -w src/ -x "run -F bevy/dynamic_linking"

[dependencies]
bevy = { version = "0.13.2", features = ["dynamic_linking"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
